name: Spring Boot CI/CD Demo

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ 소스코드 체크아웃
      - name: Checkout source
        uses: actions/checkout@v4
        
      - name: Check ROBOT_DEMO_CI Secret
        run: |
          if [ -z "${{ secrets.ROBOT_DEMO_CI }}" ]; then
            echo "ROBOT_DEMO_CI is empty"
            exit 1
          else
            echo "ROBOT_DEMO_CI exists"
          fi
