name: Spring Boot CI/CD Demo

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ 소스코드 체크아웃
      - name: Checkout source
        uses: actions/checkout@v4
        
      - name: Check HARBOR_URL Secret
        run: |
          if [ -z "${{ secrets.HARBOR_URL }}" ]; then
            echo "HARBOR_URL is empty"
            exit 1
          else
            echo "HARBOR_URL exists"
          fi
