name: Spring Boot CI/CD Demo

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: self-hosted  # self-hosted runner 사용
    
    steps:
      # 1️⃣ 소스코드 체크아웃
      - name: Checkout source
        uses: actions/checkout@v4

      # 2️⃣ JDK 설치 (Java 17) 및 Maven 캐시 설정
      - name: Set up JDK 17 and Maven
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      # 3️⃣ Maven으로 Spring Boot JAR 빌드
      - name: Build Spring Boot JAR
        run: mvn clean package -DskipTests
        working-directory: demo

      # 4️⃣ Docker 이미지 빌드
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_REGISTRY }}:${{ github.sha }} .
        working-directory: demo

      # 5️⃣ Harbor 로그인
      - name: Login to Harbor
        run: |
          echo "${{ secrets.HARBOR_PASSWORD }}" | docker login 10.0.2.15 \
            -u "${{ secrets.HARBOR_USERNAME }}" \
            --password-stdin

      # 6️⃣ Docker 이미지 Push
      - name: Push image to Harbor
        run: docker push ${{ secrets.DOCKER_REGISTRY }}:${{ github.sha }}
