name: Spring Boot CI/CD Demo

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ 소스코드 체크아웃
      - name: Checkout source
        uses: actions/checkout@v4
        
      - name: Check DOCKER_REGISTRY Secret
        run: |
          if [ -z "${{ secrets.DOCKER_REGISTRY }}" ]; then
            echo "DOCKER_REGISTRY is empty"
            exit 1
          else
            echo "DOCKER_REGISTRY exists"
          fi
